name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/notestrich-image:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/notestrich-image:$(date +'%Y%m%d%H%M%S')
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/notestrich-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notestrich-image:$(date +'%Y%m%d%H%M%S')

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/notestrich-image:latest
            docker rm -f notestrich || true
            docker run -d \
            --name notestrich \
            --restart always \
            -p 8080:80 \
            -p 8443:443 \
            -v /etc/certs:/etc/certs:ro \
            ${{ secrets.DOCKER_USERNAME }}/notestrich-image:latest
            sleep 5
            docker ps | grep notestrich || (echo "Container failed to start!" && docker logs notestrich && exit 1)
            docker inspect --format '{{json .State.Health.Status}}' notestrich | grep -q '"healthy"' || (echo "Container is not healthy!" && exit 1)
